# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size= 0.2, random_state = 0)

### Feature Scaling

In [15]:
#Feature scaling is very much compulsory in deep learning to all the independent variables

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [18]:
print(X_test)

[[-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
   1.62185911]
 [ 1.04501206 -0.61433742 -0.57427105 ...  0.66011376 -1.02429504
   0.504204  ]
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376 -1.02429504
   0.72775202]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
  -1.54162886]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376 -1.02429504
   1.62356528]]


## Part 2 - Building the ANN

### Initializing the ANN

In [19]:
# ANN model is nothing but the sequence of the layers connected togather from input,hidden upto output layer
# keras library is integrated in tensorflow
# ann(artificial neural network) is created as instance of sequential class from keras.models
# these just initialises the ANN model

ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [21]:
# dense class add fully connected layers into ANN(so fully connected layer we are about to build will be the object of dense class)
# units = 6(number of hidden layer units in first hidden layer of ANN ); activation function for hidden layers are generally rectifier (relu) function

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [22]:
# if hidden layer in ANN is 1=shallow type of ANN ; but more than 1 hidden layer is present then it becomes deep ANN,hence add second hidden layer
# change the values of hyperparameters to get different result(may be more accuarate)

ann.add(tf.keras.layers.Dense(units=6 , activation='relu'))

### Adding the output layer

In [24]:
# here we need only 1 output layer unit(neuron) as we get binary output here; but if we are gonna get classification outputs like for 3 classes seperate then we require 3 output neurons(unita)

ann.add(tf.keras.layers.Dense(units = 1, activation= 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [25]:
# compile the ANN with optimizer,loss function and metric(accuracy)
# for stochastic gradient descent which reduces the loss error, we use adam optimizer
# for binary classification(0 or 1) problem use only loss= 'binary_crossentropy'
# for other than binary classification like for categorical classification(3 or more than 3 classes) use loss ='categorical_crossentropy' and also at the output layer the activation function for categorical classification is 'softmax' rather than sigmoid

ann.compile(optimizer = 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'] )

### Training the ANN on the Training set

In [26]:
#batch size takes certain number of obeservations, and these parameter gives the number of predictions in the batch to be compared to that same number of real results(at same time)
# take batch size = 32 (generally)
# neural network has to be trained over certain number of epochs to improve the accuracy over time

ann.fit(X_train,y_train, batch_size = 32, epochs= 100 )

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5569 - accuracy: 0.7552
Epoch 2/100
250/250 [==============================] - 0s 999us/step - loss: 0.4504 - accuracy: 0.8036
Epoch 3/100
250/250 [==============================] - 0s 990us/step - loss: 0.4353 - accuracy: 0.8077
Epoch 4/100
250/250 [==============================] - 0s 980us/step - loss: 0.4290 - accuracy: 0.8116
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4246 - accuracy: 0.8155
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4211 - accuracy: 0.8189
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4171 - accuracy: 0.8242
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4133 - accuracy: 0.8270
Epoch 9/100
250/250 [==============================] - 0s 987us/step - loss: 0.4105 - accuracy: 0.8294
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4082 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [29]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))> 0.5)

[[ True]]


### Predicting the Test set results

In [30]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)                     # if y_pred(probablity) >0.5= true ie (1) else we get false ie (0)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[1524   71]
 [ 206  199]]
0.8615
