# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [ ]:
# Now we gonna do feature scaling as is it important in case of deep learning

from sklearn.preprocessing import StandardScaler
sc  = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-1.13572795 -0.88685592  0.67357894  0.52070558]
 [-0.80630243 -0.00971567  0.45145467  0.14531044]
 [ 1.77128416  1.84743445  0.24279248 -1.88374143]
 ...
 [-0.38409993 -1.24886277  0.84522042  0.13092486]
 [-0.9232821  -1.04155299  1.54693117  0.8830852 ]
 [ 1.70136528  1.05824381 -1.20438076 -2.42285818]]


In [ ]:
print(X_test)

[[ 1.20924389  1.84743445 -0.61878043 -0.28968211]
 [-0.29401214 -0.39528045  1.39211729  0.76937061]
 [-0.64629575 -0.88607065  1.00508258  1.77019599]
 ...
 [-0.99857936 -0.74629361  1.76737267  1.02146078]
 [ 1.02368993 -0.50992904 -1.64526378 -0.96443434]
 [-0.32090402 -1.13342892 -1.03442205  0.0651622 ]]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))       

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

### Adding the output layer

In [ ]:
# for regression we generally not used activation function

ann.add(tf.keras.layers.Dense(units= 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train,y_train, batch_size = 32 , epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 205324.4375
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 189414.2500
Epoch 3/100
240/240 [==============================] - 0s 955us/step - loss: 127196.6641
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 45529.9883
Epoch 5/100
240/240 [==============================] - 0s 997us/step - loss: 23248.4668
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 16517.6602
Epoch 7/100
240/240 [==============================] - 0s 954us/step - loss: 11148.0742
Epoch 8/100
240/240 [==============================] - 0s 979us/step - loss: 6964.1172
Epoch 9/100
240/240 [==============================] - 0s 961us/step - loss: 4130.8574
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 2336.9006
Epoch 11/100
240/240 [==============================] - 0s 939us/step - loss: 1291.5785
Epoch 12/100
240/240 [===================

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[430.45 431.23]
 [457.98 460.01]
 [462.42 461.14]
 ...
 [468.96 473.26]
 [441.89 438.  ]
 [461.47 463.28]]
